### ISSUE TITLE
All apps show cannot be opened error

### ISSUE THREAD

**Issue by mba08mc** [minif/iphoneos2-app-fixer#1]
iPod Touch 1G running iPhoneOS 2.0.2 with mobileinstallation 2.0.2 installed. App Store no longer works on this version so ipa file of encrypted app taken from an iPhone 3GS (app supports 2.0) is installed with finder. But even when that is opened, the cannot be opened error reappears. here is an ipa I tried.
[App.zip](https://github.com/minif/iphoneos2-app-fixer/files/11522426/App.zip)

**Comment by minif** [comment]
Since the app is encrypted I've gone ahead and decrypted the app so it can work: https://cdn.discordapp.com/attachments/894234514136629298/1109582713385656330/com.shinmira.korebasilite-iOSnull-Clutch-2.0.4.ipa

That being said this app doesn't seem to work for me on iPhone OS 2.2.1 on my Touch 2, but let me know if it works for you anyways. (It is the case where the app immediately crashes when opened, I have no clue what causes this)

BTW, does this app work on the 3GS?

**Comment by minif** [comment]
Also, let me know if any other apps work, such as this one which I know works for me: https://cdn.discordapp.com/attachments/733735735781359656/1109587260002795540/JellyCar_1.2_Decrypted.ipa

**Comment by mba08mc** [comment]
sure I will try the app ou have sent and I will notify you of any changes. thanks a lot

**Comment by mba08mc** [comment]
> Also, let me know if any other apps work, such as this one which I know works for me: https://cdn.discordapp.com/attachments/733735735781359656/1109587260002795540/JellyCar_1.2_Decrypted.ipa

It requires a newer version of iOS. Probably supports 2.2.1 and up

**Comment by minif** [comment]
Update on this (and apologies for the long delay, I've been busy). I now have a better understanding of the issue and a possible solution.

If you have filesystem access, there should be a file at /var/mobile/Library/Caches/ called com.apple.mobile.installation.composite_trust.plist. Does this file have Apple iPhone OS Application Signing set to true? (The composite_trust file should be around 85 bytes, not 42 bytes).

If not, and if you are still wanting to try to get the app working, try replacing it with this file: https://github.com/minif/iphoneos2-app-fixer/raw/master/com.apple.mobile.installation.composite_trust.plist

**Comment by minif** [comment]
Depending on how you view .plist files it might look like this:
![Screenshot 2024-05-24 at 10 05 09 PM](https://github.com/minif/iphoneos2-app-fixer/assets/19511875/93870e21-4058-4213-a715-253ae8f5bf28)

**Comment by mba08mc** [comment]
Thanks, I'll take a look at this. Surprised you even remembered this issue after a year : )
